# Generated by Django 3.2 on 2021-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=20)),
                ('std_name', models.CharField(max_length=45)),
                ('std_age', models.IntegerField()),
                ('std_city', models.CharField(max_length=50)),
                ('std_email', models.CharField(max_length=50)),
                ('std_contact', models.CharField(max_length=50)),
                ('std_dob', models.CharField(max_length=50)),
            ],
        ),
    ]
